bonus/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import include

urlpatterns = [
    path('', views.index, name='index'),
    path('prizes/',views.PrizeListView.as_view()),
    path('prizes/<int:pk>',views.PrizeDetailView.as_view(), name='prize_detail'),
]

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path('show/',views.show_apply,name='show'),
]

# test

vh5000/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('',include('register.urls')),
    path('admin/', admin.site.urls),
    path('apply/',include('register.urls')),
    path('bonus/', include('bonus.urls')),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

bonus/models.py
from django.db import models
from django.urls import reverse

class Prize(models.Model):
    pid = models.CharField(max_length=25)
    cname = models.CharField(max_length=20)
    amount = models.IntegerField()
    desc = models.TextField(null=True,blank=True)
    img = models.ImageField(upload_to = "images/",null = True,blank=True)

    def get_url(self):
        return reverse('prize_detail',args=[str(self.id)])
    
    class Meta:
        ordering = ['-amount']

    def __str__(self):
        return self.cname


class Winner(models.Model):
    prize_id = models.ForeignKey(
        "Prize", on_delete=models.CASCADE)
    week = models.CharField(max_length=1,default='1')

    last_ssn = models.CharField(max_length=3)

    class Meta:
        ordering = ['week','prize_id']

    def __str__(self):
        return self.prize_id.cname + ", Week " + self.week  + ", "+ self.last_ssn

register/models.py
from django.db import models

class Person(models.Model):
    VOUCHER_CHOICES = [
        ('PP','紙本'),
        ('CC','信用卡'),
        ('ET','電子票券'),
        ('MB','行動支付')
    ]
    ssn = models.CharField(max_length=10,blank = False)
    tel = models.CharField(max_length=20,blank=False)
    voucher_id = models.CharField(max_length=2,choices=VOUCHER_CHOICES,default='PP')

    class Meta:
        ordering = ['-ssn']
    def __str__(self):
        return self.ssn

register/forms.py
from django import forms
from django.conf.urls.static import static
from .models import Person
from django.core.exceptions import ValidationError

class PersonModelForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['ssn','tel','voucher_id']

        widgets = {
            'ssn' : forms.TextInput(attrs={'class':'form-control'}),
            'tel' : forms.TextInput(attrs = {'class':'form-control'}),
            'voucher_id' : forms.RadioSelect()
        }

        labels = {
            'ssn':'身分證字號',
            'tel':'電話號碼',
            'voucher':'綁定'
        }
    def clean_ssn(self):
        data = self.cleaned_data['ssn']

        if len(data) != 10 :
            raise ValidationError('身分證長度必為 10')
        return data
        
    def clean_tel(self):
        data = self.cleaned_data['tel']

        if len(data) < 5 :
            raise ValidationError('電話長度不可小於5')
        return data

bonus/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from .models import Prize, Winner


def index(request):
    prizeList = Prize.objects.all()
    winnerList = Winner.objects.all()
    winnerListDict = {} # 由 pid 取得獲獎者的 list
    prizeCNameDict = {} # 由 pid 取得 p cname

    for p in prizeList:
        wList = [w.last_ssn for w in Winner.objects.filter(prize_id=p)]
        winnerListDict[p.pid] = wList
        prizeCNameDict[p.pid] = p.cname
    
    print (str(winnerListDict))
    print (str(prizeCNameDict))
    
    return render(
        request,
        'bonus/index.html',
        context={'winnerList_dict': winnerListDict,
                 'prizeCName_dict': prizeCNameDict,}
    )


from django.views.generic import ListView
from django.views.generic import DetailView

class PrizeListView(ListView):
    model = Prize
    template_name = 'bonus/prize_list.html'
    context_object_name = 'prize_list'
    def get_queryset(self):
        return Prize.objects.order_by('-amount')[:3]

class PrizeDetailView(DetailView):
    model = Prize

register/views.py
from django.shortcuts import render
from .models import Person
from .forms import PersonModelForm
from django.http import request


def index(request):
    if request.method == "POST":
        form = PersonModelForm(request.POST)
        if form.is_valid():
            form.save()
            context = {'form':form}
            return render(request,"register/apply_success.html",context)
        else:
            return render(request,"register/apply_fail.html",context)
    form = PersonModelForm()
    context = {
        'form':form
    }
    
    return render(request, "register/apply.html", context)


def show_apply(request):
    person_list = Person.objects.all()
    context = {
        'person_list': person_list
    }
    return render(request, "register/show.html", context)

bonus/templates/bonus/index.html
{% extends "base.html" %} {% load dict_tag %} {% block prize_desc %} {% load static %}
<!-- <img class="rounded mx-auto d-block" src="{% static 'images/drawPrize.jpeg' %}" width="600"> -->
<img class="rounded mx-auto d-block" src="/static/images/drawPrize.jpeg" width="600"> {% endblock %} {% block prize %}

<h3 class="text-center" style="margin-top: 50px;"> 獎項超級多，你中獎了嗎？ </h3>

<div class="row" id="winner_list">
    {% for pid, winners in winnerList_dict.items %}
    <div class='col-6 col-sm-4 col-md-3'>
        <div class="logo div">
            {% load static %} {% with 'images/'|add:pid|add:'.png' as image_static %}
            <img src={% static image_static %} class="img-fluid"> {% endwith %}
        </div>

        <div class="winner-list container">
            <p> {{ prizeCName_dict | get_value_from_dict:pid}} </p>
            {% for w in winners %}
            <div class="winner">{{w}} </div>{% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

bonus/templates/bonus/prize_detail.html
{% extends "base.html" %} {% block prize %}
<img src="{{ prize.img.url}}" width='200px' alt="logo">
<h5> {{prize.cname}} </h5>
<p>金額：{{prize.amount}}</p>
<p>{{prize.desc}} </p>
{% endblock %}

bonus/templates/bonus/prize_list.html
{% extends "base.html" %} {% block prize%}
<h3>獎項多多</h3>
<p>本次活動共有以下的獎項：</p>
{% if prize_list %}
<ul>
    {% for prize in prize_list %}
    <li><a href="{{ prize.get_url }}"> {{ prize.cname }}</a>：金額：{{prize.amount}} 元 {% endfor %}
</ul>
{% else %}
<p>There are no prize.</p>
{% endif %} {% endblock %}

register/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>五倍劵</title>

    <style>
        .sidebar-nav {
            margin-top: 40px;
            padding: 0;
            list-style: none;
        }
        
        .center-block {
            margin-left: auto;
            margin-right: auto;
            display: block;
        }
        
        .logo {
            margin: 20px;
        }
        
        .winner-list {
            text-align: left;
        }
        
        .winner {
            margin: 1px;
            border-radius: 100%;
            border-style: solid;
            border-color: antiquewhite;
            padding: 5px;
            font-size: 30px;
            color: red;
            display: inline-block;
        }
    </style>

</head>

<body>

    <div class="container-fluid">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1 class="display-4">五倍劵，讓你不疲倦</h1>
                <p class="lead">還有加碼卷，週週開獎，讓你好運領不完</p>
            </div>
        </div>

        <div class="container">
            {% block prize_desc %}{% endblock %}
        </div>

    </div>

    <div class="container-fluid">

        <div class="row">
            <div class="col-sm-1">
                <ul class="sidebar-nav">
                    <li><a href="/">HOME</a></li>
                </ul>
                <h5>五倍劵</h5>
                <ul class="sidebar-nav">
                    <li><a href="/apply">申請綁定</a></li>
                </ul>
                <h5>加碼劵</h5>
                <ul class="sidebar-nav">
                    <li><a href="/bonus/how">怎麼抽</a></li>
                    <li><a href="/bonus">第一週</a></li>
                    <li><a href=".">第二週</a></li>
                    <li><a href=".">第三週</a></li>
                    <li><a href=".">第四週</a></li>
                    <li><a href=".">幸運表</a></li>
                </ul>
                <hr>
                <a href="/admin">admin</a>
            </div>

            <div class="col-sm-11">


                <div class="container">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <hr>
        <p>Web programming, IECS, FCU, 2021</p>
    </div>


</body>

</html>

register/templates/register/apply.html
{% extends "base.html" %} {% block content %}
<form action="" method="POST">
    {% csrf_token %} {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="提交" />

</form>

{% endblock %}

register/templates/register/apply_fail.html
{% extends "base.html" %} {% block content %}

<p>資料輸入錯誤</p>

{{ form.errors }} {% endblock %}

register/templates/register/apply_success.html
{% extends "base.html" %} {% block content %}

<p>綁定成功</p>

<ul>
    <li> {{form.ssn.label}}: {{form.ssn.value}}
        <li> {{form.tel.label}}: {{form.tel.value}}
            <li> {{form.voucher_id.label}}: {{form.voucher_id.value}}
</ul>

{% endblock %}

register/templates/register/show.html
{% block content %}
<h3>目前的綁定狀況</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>身分證</th>
            <th>電話</th>
            <th>綁定模式</th>
        </tr>
    </thead>
    <tbody>
        {% for p in person_list %}
        <tr>
            <td>{{ p.ssn }}</td>
            <td>{{ p.tel }}</td>
            <td>{{ p.get_voucher_id_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}